behaviors:
  NPC Controller:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 40960
      learning_rate: 5.0e-4
      beta: 5.0e-4
      epsilon: 0.1
      lambd: 0.95
      num_epoch: 7
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256  
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 42000000
    time_horizon: 128
    summary_freq: 100000 
    keep_checkpoints: 50
    threaded: True
